### ISSUE TITLE
SDK installation fails

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#1635]
## Steps to Reproduce
1. Clone repo to new machine 
2. try installing the sdk `cd light-client/raiden-ts && npm ci`

## Expected Result
- Flawless installation of dependencies

## Actual Result
```
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/home/oliver/Arbeit/github/iblockchain/400_Work-Packages/AP4/codebase/light-client/raiden-ts/raiden-contracts/raiden_contracts/data/'
    at Object.readdirSync (fs.js:948:3)
    at preBuild (/home/oliver/Arbeit/github/iblockchain/400_Work-Packages/AP4/codebase/light-client/raiden-ts/scripts/copyContracts.js:25:6)
    at Object.<anonymous> (/home/oliver/Arbeit/github/iblockchain/400_Work-Packages/AP4/codebase/light-client/raiden-ts/scripts/copyContracts.js:70:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/oliver/Arbeit/github/iblockchain/400_Work-Packages/AP4/codebase/light-client/raiden-ts/raiden-contracts/raiden_contracts/data/'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raiden-ts@0.9.0 contracts:pre: `node ./scripts/copyContracts.js prebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raiden-ts@0.9.0 contracts:pre script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_cacache/_logs/2020-06-04T11_43_09_556Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raiden-ts@0.9.0 contracts: `npm run contracts:pre && npm run contracts:build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raiden-ts@0.9.0 contracts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_cacache/_logs/2020-06-04T11_43_09_564Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raiden-ts@0.9.0 build: `npm run versions && npm run contracts && tsc -p src/tsconfig.json && tsc -p src/tsconfig.cjs.json && npm run contracts:post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raiden-ts@0.9.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_cacache/_logs/2020-06-04T11_43_09_571Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! raiden-ts@0.9.0 prepare: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raiden-ts@0.9.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oliver/.npm/_logs/2020-06-04T11_43_09_597Z-debug.lo
```

## Additional Infos (Optional) 
```
oliver@bbpc:~/Arbeit/github/iblockchain/400_Work-Packages/AP4/codebase/light-client/raiden-ts$ uname -a
Linux bbpc 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
oliver@bbpc:~/Arbeit/github/iblockchain/400_Work-Packages/AP4/codebase/light-client/raiden-ts$ node --version && npm -v
v12.18.0
6.14.4
```

[2020-06-04T11_43_09_597Z-debug.log](https://github.com/raiden-network/light-client/files/4729692/2020-06-04T11_43_09_597Z-debug.log)

**Comment by andrevmatos** [comment]
You forgot to `git submodule sync && git submodule update` on the `raiden-ts` folder before trying to build (which is also done on the end of `npm ci` or `npm install`). Update the submodules and it'll work. Reopen if the issue persists.
