### ISSUE TITLE
CLI- opening channel fails

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#1830]
## Steps to Reproduce
1. Build cli and try to open a channel
2. `http PUT localhost:5001/api/v1/channels partner_address=0x002857f3a3BEa9DC0301D6DCf573692720f88B5a total_deposit=100000 token_address=0x59105441977ecD9d805A4f5b060E34676F50F806`

## Expected Result
- 200 Response

## Actual Result
```
pi@NanoPi-Duo2:~/light-client$ http PUT localhost:5001/api/v1/channels partner_address=0x002857f3a3BEa9DC0301D6DCf573692720f88B5a total_deposit=100000 token_address=0x59105441977ecD9d805A4f5b060E34676F50F806
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 148
Content-Security-Policy: default-src 'none'
Content-Type: text/html; charset=utf-8
Date: Mon, 29 Jun 2020 16:12:17 GMT
X-Content-Type-Options: nosniff
X-Powered-By: Express

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```

## Additional Infos (Optional) 

My nodes address: https://goerli.etherscan.io/address/0x00d384ef74575e97884215e9f39142228c7acfa8

[Full log files](https://github.com/raiden-network/light-client/files/4846767/raiden.zip)
There's a lot of trash in the logs (check out the last 20 minutes of the logfile. I also tried multiple other requests.
The right part should be:
```
Jun 29 16:09:44 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959475 } }
Jun 29 16:10:00 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959476 } }
Jun 29 16:10:12 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959477 } }
Jun 29 16:10:28 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959478 } }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   type: 'token/monitored',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   payload: {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     fromBlock: 2723614
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   type: 'token/monitored',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   payload: {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     fromBlock: 2723615,
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     toBlock: 2959478
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   type: 'channel/open/request',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   payload: { settleTimeout: undefined, deposit: e { _hex: '0x0186a0' } },
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   meta: {
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:     partner: '0x002857f3a3BEa9DC0301D6DCf573692720f88B5a'
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:10:38 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   type: 'channel/deposit/failure',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   payload: Error: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing t
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at m (/home/pi/light-client/raiden-cli/build/bundle.js:82:283353)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at t.XMLHttpRequest.s.onreadystatechange (/home/pi/light-client/raiden-cli/build/bundle.js:82:281777)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at t.XMLHttpRequest.dispatchEvent (/home/pi/light-client/raiden-cli/build/bundle.js:373:5991)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at b (/home/pi/light-client/raiden-cli/build/bundle.js:373:6177)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at IncomingMessage.<anonymous> (/home/pi/light-client/raiden-cli/build/bundle.js:373:3744)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at IncomingMessage.emit (events.js:322:22)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at endReadableNT (_stream_readable.js:1187:12)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     code: -32010,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     data: undefined,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     url: 'http://parity.goerli.ethnodes.brainbot.com:8545',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     body: '{"method":"eth_sendRawTransaction","params":["0xf8a81d847735940082abef9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b30000000000000000000000003ea2a
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     responseText: '{"jsonrpc":"2.0","error":{"code":-32010,"message":"Transaction gas price supplied is too low. There is another transaction with same nonce in the q
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     transaction: {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       nonce: 29,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       gasPrice: [e],
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       gasLimit: [e],
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       to: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       value: [e],
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       data: '0x095ea7b30000000000000000000000003ea2a1fed7fdef300da19e97092ce8fdf8bf66a300000000000000000000000000000000000000000000000000000000000186a0',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       chainId: 5,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       v: 46,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       r: '0x600fa48354d67b0b989565e6e64487e002b41205bef6b72ca8cf9e9d89da3946',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       s: '0x05045c8084992e48df1db4db6334afdab4eea6cdc620e6b5f7595c6f292a82b6',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       from: '0x00D384EF74575E97884215e9f39142228c7ACfa8',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:       hash: '0x1f233f6a33060a00a8091b1cd5715a339c0e89a95cce0a6941f30970dce78b44'
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     },
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     transactionHash: '0x1f233f6a33060a00a8091b1cd5715a339c0e89a95cce0a6941f30970dce78b44'
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   },
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   meta: {
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     partner: '0x002857f3a3BEa9DC0301D6DCf573692720f88B5a'
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   },
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:   error: true
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: (node:3133) UnhandledPromiseRejectionWarning: Error: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increas
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at m (/home/pi/light-client/raiden-cli/build/bundle.js:82:283353)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at t.XMLHttpRequest.s.onreadystatechange (/home/pi/light-client/raiden-cli/build/bundle.js:82:281777)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at t.XMLHttpRequest.dispatchEvent (/home/pi/light-client/raiden-cli/build/bundle.js:373:5991)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at b (/home/pi/light-client/raiden-cli/build/bundle.js:373:6177)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at IncomingMessage.<anonymous> (/home/pi/light-client/raiden-cli/build/bundle.js:373:3744)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at IncomingMessage.emit (events.js:322:22)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at endReadableNT (_stream_readable.js:1187:12)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: (node:3133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block,
Jun 29 16:10:40 NanoPi-Duo2 raiden.sh[3128]: (node:3133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.
Jun 29 16:10:44 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959479 } }
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959480 } }
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:  action     {
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   type: 'channel/open/success',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   payload: {
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     id: 3063,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     token: '0x59105441977ecD9d805A4f5b060E34676F50F806',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     settleTimeout: 500,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     isFirstParticipant: true,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     txHash: '0xedfb0191a1f3f007365987d975bc86c7da9d797b98fb5ca6dbae23a96e466b7c',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     txBlock: 2959480,
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     confirmed: undefined
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   },
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   meta: {
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:     partner: '0x002857f3a3BEa9DC0301D6DCf573692720f88B5a'
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]:   }
Jun 29 16:11:00 NanoPi-Duo2 raiden.sh[3128]: }
Jun 29 16:11:16 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959481 } }
Jun 29 16:11:28 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959482 } }
Jun 29 16:11:44 NanoPi-Duo2 raiden.sh[3128]:  action     { type: 'block/new', payload: { blockNumber: 2959483 } }
```

## Remarks
It looks to me as if the SDK tries to use the same nonce for deposit as it used for the openChannel Tx.
CC @weilbith - we briefly talked about the issue

**Comment by andrevmatos** [comment]
Not the deposit, but the `approve`. Yes, `open` and `approve` are sent almost at the same time, as an optimization, to be mined in parallel. Usually, we don't set a nonce, and instead rely on `ethers` fetching the latest nonce with `getTransactionCount`. This works fine most of the time, and here, since I send the `approve` only after the `open` tx was **sent** (but not mined), I assumed it'd work as well, and it does on Metamask. Looks like it doesn't on your node.
The quick fix is to get `nonce` out of the `open` tx just sent, increment and pass it to the `approve` tx explicitly.

**Comment by weilbith** [comment]
Small addition: @eorituz was using our company internal Ethereum nodes. So either Parity or Geth.

**Comment by eorituz** [comment]
I used the bbot internal `goerli.parity...` node

**Comment by weilbith** [comment]
[It works](https://github.com/raiden-network/light-client/pull/1833#issuecomment-651682879).
So @eorituz if you can't await this PR to get merged, feel free to checkout the branch of the PR. Don't forget to use the correct contract version. :wink:

**Comment by eorituz** [comment]
I can confirm that the fix works

**Comment by andrevmatos** [comment]
The PR didn't get merged yet ;)
