### ISSUE TITLE
dApp: getMainAccount not a function TypeErrors during unit tests

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2182]
## Steps to Reproduce
1. Run the unit tests
2. Get a mass of red text with warnings

## Expected Result
- Test output is clean
- Developer do not get used to this and possibly oversee actual new issues

## Actual Result
- many errors

**Comment by weilbith** [comment]
Errors look like this:

```sh
  console.error
    TypeError: this.$raiden.getMainAccount is not a function
        at VueComponent.mounted (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-dapp/src/components/dialogs/UdcDepositDialog.vue:161:1)
        at invokeWithErrorHandling (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:1850:57)
        at callHook (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:4207:7)
        at Object.insert (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:3133:7)
        at invokeInsertHook (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:6326:28)
        at VueComponent.patch [as __patch__] (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:6543:5)
        at VueComponent.Vue._update (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
        at VueComponent.updateComponent (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
        at Watcher.get (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
        at new Watcher (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
        at mountComponent (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
        at VueComponent.Vue.$mount (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
        at mount (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/@vue/test-utils@1.1.0_ae554d8947d7e926b014dda25865f517/node_modules/@vue/test-utils/dist/vue-test-utils.js:13935:21)
        at createWrapper (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-dapp/tests/unit/views/transfer-steps-route.spec.ts:68:12)
        at Object.<anonymous> (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-dapp/tests/unit/views/transfer-steps-route.spec.ts:279:21)
        at Object.asyncJestTest (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/jest-jasmine2@26.4.2/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
        at /home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/jest-jasmine2@26.4.2/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/jest-jasmine2@26.4.2/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/thore/projects/brainbot-projects/repositories/raiden/light-client/node_modules/.pnpm/jest-jasmine2@26.4.2/node_modules/jest-jasmine2/build/queueRunner.js:75:41

      at logError (../node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:1884:13)
      at globalHandleError (../node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:1875:3)
      at handleError (../node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:1835:5)
      at ../node_modules/.pnpm/vue@2.6.12/node_modules/vue/dist/vue.runtime.common.dev.js:1852:39
```
