### ISSUE TITLE
Handle ETH node connection problems gracefully

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2240]
## Thanks for filing a bug report :-)

During the nightly run the PFS8 scenario failed.

Might be related to https://github.com/raiden-network/raiden/issues/6612

The light client seems to have crashed and returned a 500 error code
```
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:56049/api/v1/channels. Expected 201: <!DOCTYPE html>
<html lang=\"en\">
<head>
<meta charset=\"utf-8\">
<title>Error</title>
</head>
<body>
<pre>InternalServerError: invalid response - 0
    at Object.internalErrorHandler (/lc/index.js:221624:31)
    at Layer.handle_error (/lc/index.js:47797:5)
    at trim_prefix (/lc/index.js:47371:13)
    at /lc/index.js:47340:7
    at Function.process_params (/lc/index.js:47391:12)
    at next (/lc/index.js:47331:10)
    at Layer.handle_error (/lc/index.js:47793:12)
    at trim_prefix (/lc/index.js:47371:13)
    at /lc/index.js:47340:7
    at Function.process_params (/lc/index.js:47391:12)</pre>
</body>
</html>
```

Logs:
[scenario-player-run_pfs8_mediator_goes_offline_2020-10-13T16:24:55.log.gz](https://github.com/raiden-network/light-client/files/5376971/scenario-player-run_pfs8_mediator_goes_offline_2020-10-13T16.24.55.log.gz)

## Expected Result
- Scenario should pass

**Comment by andrevmatos** [comment]
@palango The SP logs aren't very useful here. Can you please provide the `.log` files from the clients?

**Comment by palango** [comment]
@andrevmatos This is the end of the logs of node 0, to whom the request went:
```
127.0.0.1 - - "PUT /api/v1/channels HTTP/1.1" 201 375 "-" "python-requests/2.24.0"
2020-10-13T16:29:58.817Z [info] Couldn't set up WebRTC dataChannel, retrying 0x14a3e093c503b00ad3ef8d88a06be599474441e6|0xbc9a89ec87c86736bf39ff7143fe2f16f49ac879 RTC: dataChannel closed
2020-10-13T16:29:58.817Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'rtc/channel',
  payload: undefined,
  meta: { address: '0x14A3E093c503B00aD3ef8D88a06be599474441e6' }
}
2020-10-13T16:29:58.820Z [info] Couldn't set up WebRTC dataChannel, retrying 0xa63ffd5bfdf2e2e188fdd73a0f48d291d099bca8|0xbc9a89ec87c86736bf39ff7143fe2f16f49ac879 RTC: dataChannel closed
2020-10-13T16:29:58.821Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'rtc/channel',
  payload: undefined,
  meta: { address: '0xa63Ffd5Bfdf2e2E188FDd73A0F48D291d099BCA8' }
}
2020-10-13T16:29:58.822Z [info] Stopping raiden...
2020-10-13T16:29:58.823Z [info] Closing server...
2020-10-13T16:29:58.827Z [info] %c action     color: #03A9F4; font-weight: bold { type: 'raiden/shutdown', payload: { reason: 'raidenStopped' } }
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Here are all node logs:
[node_logs.zip](https://github.com/raiden-network/light-client/files/5378919/node_logs.zip)

**Comment by palango** [comment]
This happened again in todays BF3 scenario:
```
{"result": "scenario error", "message": "HTTP status code \"500\" while fetching http://127.0.0.1:39275/api/v1/channels/0x59105441977ecD9d805A4f5b060E34676F50F806/0x460d0eCe930f9982CfBeE6aD8EFcc8dc71d568eE. Expected 200:
 <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: timeout
     at Object.internalErrorHandler (/lc/index.js:222590:31)
     at Layer.handle_error (/lc/index.js:47797:5)
     at trim_prefix (/lc/index.js:47371:13)
     at /lc/index.js:47340:7
     at Function.process_params (/lc/index.js:47391:12)
     at next (/lc/index.js:47331:10)
     at Layer.handle_error (/lc/index.js:47793:12)
     at trim_prefix (/lc/index.js:47371:13)
     at /lc/index.js:47340:7
     at Function.process_params (/lc/index.js:47391:12)</pre>\n</body>\n</html>\n",
"event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2020-10-15 12:40:56.307140"
```

**Comment by andrevmatos** [comment]
Better reading node0's logs, I found the culprit:
```
2020-10-13T16:26:46.111Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'channel/open/failed',
  payload: Error: invalid response - 0
      at exports.XMLHttpRequest.request.onreadystatechange (/lc/index.js:42562:29)
      at exports.XMLHttpRequest.dispatchEvent (/lc/index.js:202325:25)
      at setState (/lc/index.js:202344:14)
      at exports.XMLHttpRequest.handleError (/lc/index.js:202266:5)
      at ClientRequest.errorHandler (/lc/index.js:202193:14)
      at ClientRequest.emit (events.js:314:20)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:314:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3) {
    statusCode: 0,
    responseText: 'Error: getaddrinfo ENOTFOUND geth.goerli.ethnodes.brainbot.com\n' +
      '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)'
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    partner: '0xa63Ffd5Bfdf2e2E188FDd73A0F48D291d099BCA8'
  },
  error: true
}
127.0.0.1 - - "PUT /api/v1/channels HTTP/1.1" 500 745 "-" "python-requests/2.24.0"
InternalServerError: invalid response - 0
    at Object.internalErrorHandler (/lc/index.js:221624:31)
    at Layer.handle_error (/lc/index.js:47797:5)
    at trim_prefix (/lc/index.js:47371:13)
    at /lc/index.js:47340:7
    at Function.process_params (/lc/index.js:47391:12)
    at next (/lc/index.js:47331:10)
    at Layer.handle_error (/lc/index.js:47793:12)
    at trim_prefix (/lc/index.js:47371:13)
    at /lc/index.js:47340:7
    at Function.process_params (/lc/index.js:47391:12)
```

This error is a network error while communicating with the ETH node (like the others we've been fixing, as part of #1790). More specifically, looks like a DNS resolve issue on the VPN/private network. I've worked around it locally by using a DNS caching service on my machine.

I've seen these errors before, and have fixed the places on "normal operation" which crashed the node when encountering it, but it's harder to guard on every place eth rpc calls are made. In this case, it happened while polling for something on the channelOpen operation, and caused it to fail (as expected: unknown errors become failure actions).

The actual fix should be something like:
- [ ] Ensure our testing network is healthy and these random DNS errors don't pop up (cc @ulope)
- [ ] Check and ensure tx sending/polling/waiting observables can handle and retry these kind of errors
  - We already have code to retry txs on tx errors, but this one shouldn't retry the whole tx, and instead just the failed request, probably on `tx.wait()`
- [ ] Check and ensure other non-tx/pure polling calls are also guarded and cleanly retry this kind of error
