### ISSUE TITLE
BF7, BF1 gets Requested target is offline

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2305]
## Thanks for filing a bug report :-)
Failure date 31st October 2020
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
`HTTP status code “409” while fetching http://127.0.0.1:32875/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xCF6d21f484b80157315750d06cE27BAdACe69fd4. Expected 200: {“message”:”The requested target is offline.”,”details”:””}`

**Comment by christianbrb** [comment]
Merge with https://github.com/raiden-network/light-client/issues/2294

**Comment by christianbrb** [comment]
Also happened on 28.10.2020 in BF1

```
HTTP status code “409” while fetching http://127.0.0.1:57957/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xcb902E222EA41EdB748b31c3425E3736Ac08d60A. Expected 2..: {“message”:”The requested target is offline.”,”details”:””}
```

**Comment by andrevmatos** [comment]
We need the nodes logs, but this error looks like the presence issue, but on our side. We've tried to workaround this bug in our side by explicitly requesting the presence on each presence's update, but looks like this isn't failproof. Proper fix is on infra/server side. I'll check if there's anything else we can do.

**Comment by christianbrb** [comment]
The last three nights we had green scenarios. Closing.

**Comment by agatsoh** [comment]
This re-occured today on BF7 at transfer task
```
- serial:
          name: "Make one transfer from node0 to node1"
          tasks:
            - transfer: {from: 0, to: 1, amount: 1_000_000_000_000_000, expected_http_status: 200}
      - wait: 100
```

```
{
  "task": "<TransferTask: {'from': 0, 'to': 1, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 155626146281000001}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2021-01-28 22:17:52.567505",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:44555/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x81382fb651011FEaba5a6652026600e8129Fb4b4. Expected 200: {\"message\":\"The requested target is offline.\",\"details\":\"\"}"
}
```


In node0
```
2021-01-28T22:17:52.562Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'path/find/failure',
  payload: RaidenError: The requested target is offline.
      at Object.assert (/lc/index.js:255255:23)
      at validateRouteTargetAndEventuallyThrow (/lc/index.js:249731:13)
      at getRoute$ (/lc/index.js:249669:5)
      at MergeMapSubscriber.project (/lc/index.js:249189:95)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:204295:27)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:204285:18)
      at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:199054:18)
      at Observable._subscribe (/lc/index.js:209326:20)
      at Observable._trySubscribe (/lc/index.js:198451:25)
      at Observable.subscribe (/lc/index.js:198437:22) {
    details: { target: '0x81382fb651011FEaba5a6652026600e8129Fb4b4' }
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    target: '0x81382fb651011FEaba5a6652026600e8129Fb4b4',
    value: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true }
  },
  error: true
}
```
In node1 no apparent reason in the logs for shutting down

**Comment by taleldayekh** [comment]
PFS issues related, not relevant for the LC team.
