### ISSUE TITLE
BF6 failure because of invalid password

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2344]
The BF6 scenario failed because a node shut down unexpectedly:
```
{"args": ["/lc/raiden", "--accept-disclaimer", "--datadir", "/data/scenarios/bf6_stress_hub_node/node_4456_004", "--keystore-path", "/data/scenarios/bf6_stress_hub_node/node_4456_004/keys", "--address", "0xaa4C87f4D26C36a3AF4d968bb3550962CD25E3f9", "--password-file", "/data/scenarios/bf6_stress_hub_node/node_4456_004/password.txt", "--network-id", "5", "--sync-check", "--gas-price", "fast", "--eth-rpc-endpoint", "http://geth.goerli.ethnodes.brainbot.com:8545", "--log-config", ":info,raiden:debug,raiden_contracts:debug,raiden.api.rest.pywsgi:warning", "--log-json", "--log-file", "/data/scenarios/bf6_stress_hub_node/node_4456_004/run-4456.log", "--disable-debug-logfile", "--matrix-server", "https://transport.transport01.raiden.network", "--api-address", "127.0.0.1:45687", "--no-web-ui", "--pathfinding-service-address", "https://pfs.transport01.raiden.network", "--pathfinding-max-paths", "5", "--proportional-fee", "0x59105441977ecD9d805A4f5b060E34676F50F806", "0", "--pathfinding-max-fee", "50000000000000000", "--gas-price", "fast", "--proportional-imbalance-fee", "0x59105441977ecD9d805A4f5b060E34676F50F806", "0", "--enable-monitoring", "--routing-mode", "pfs", "--environment-type", "development"], "exit_code": 2, "event": "Process died! Bailing out.", "logger": "raiden.utils.nursery", "level": "error", "timestamp": "2020-11-10 02:10:14.280660"}
```

The `stderr`looks like:
```
--------- Starting ---------
Main error: Error: Could not decrypt keystore for "0xaa4C87f4D26C36a3AF4d968bb3550962CD25E3f9" with provided password
    at getWallet (/lc/index.js:223009:11)
    at async main (/lc/index.js:223098:20)

```

Logs:
[Archive.zip](https://github.com/raiden-network/light-client/files/5516331/Archive.zip)

**Comment by palango** [comment]
Same happened at PFS5:

```
--------- Starting ---------
Main error: Error: Could not decrypt keystore for "0x386CffED3a62CEb9A8637419fA9E7c4EdBCfEA41" with provided password
    at getWallet (/lc/index.js:223009:11)
    at async main (/lc/index.js:223098:20)
```

Logs.
[Archive.zip](https://github.com/raiden-network/light-client/files/5516395/Archive.zip)

**Comment by andrevmatos** [comment]
Ok, it seems `ethers.Wallet` fails to open/decrypt **some** private keys generated by the SP with the following error:
```
Uncaught Error: invalid counter bytes size (must be 16 bytes)
    at Counter.setBytes (/mnt/sec/Dev/brainbot/light-client/node_modules/aes-js/index.js:645:19)
    at new Counter (/mnt/sec/Dev/brainbot/light-client/node_modules/aes-js/index.js:626:18)
    at _decrypt (/mnt/sec/Dev/brainbot/light-client/node_modules/@ethersproject/json-wallets/lib/keystore.js:95:23)
    at _getAccount (/mnt/sec/Dev/brainbot/light-client/node_modules/@ethersproject/json-wallets/lib/keystore.js:107:22)
    at Object.decryptSync (/mnt/sec/Dev/brainbot/light-client/node_modules/@ethersproject/json-wallets/lib/keystore.js:215:12)
    at Object.decryptJsonWalletSync (/mnt/sec/Dev/brainbot/light-client/node_modules/@ethersproject/json-wallets/lib/index.js:35:27)
    at Function.Wallet.fromEncryptedJsonSync (/mnt/sec/Dev/brainbot/light-client/node_modules/@ethersproject/wallet/lib/index.js:222:42)
```
This happens because the `aes-js` library **requires** the JSON wallet to be a fully compliant json-encrypted private key, and on this specific case, it seems SP generated a JSON where the `crypto..cipherparams.iv` field has only 15bytes, while it's expected to be 16bytes long. This happens because it did strip the leading zeros. I'll try to apply the correct padding before processing the JSON.
