### ISSUE TITLE
BF4 scenario failure: InternalServerError after timeout

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2388]
Konrad started the scenarios after another synapse change.

The run of BF4 showed a problem after a timeout when connecting to the geth node.

```
127.0.0.1 - - "PUT /api/v1/channels HTTP/1.1" 500 1038 "-" "python-requests/2.25.0"
InternalServerError: timeout (requestBody="{\"method\":\"eth_gasPrice\",\"params\":[],\"id\":610,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="http://geth.goerli.ethnodes.brainbot.com:8545", code=TIMEOUT, version=web/5.0.10)
    at Object.internalErrorHandler (/lc/index.js:254559:31)
    at Layer.handle_error (/lc/index.js:56941:5)
    at trim_prefix (/lc/index.js:56515:13)
    at /lc/index.js:56484:7
    at Function.process_params (/lc/index.js:56535:12)
    at next (/lc/index.js:56475:10)
    at Layer.handle_error (/lc/index.js:56937:12)
    at trim_prefix (/lc/index.js:56515:13)
    at /lc/index.js:56484:7
    at Function.process_params (/lc/index.js:56535:12)
2020-11-23T14:08:28.713Z [info] %c action     color: #03A9F4; font-weight: bold { type: 'block/new', payload: { blockNumber: 3804541 } }
2020-11-23T14:08:28.729Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'channel/deposit/failure',
  payload: RaidenError: No open channel has been found.
      at MergeMapSubscriber.project (/lc/index.js:239088:105)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:203385:27)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:203375:18)
      at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198144:18)
      at ThrowIfEmptySubscriber.module.exports.__webpack_modules__.31878.ThrowIfEmptySubscriber._next (/lc/index.js:206073:26)
      at ThrowIfEmptySubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198144:18)
      at TakeSubscriber.module.exports.__webpack_modules__.23260.TakeSubscriber._next (/lc/index.js:205487:30)
      at TakeSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198144:18)
      at CombineLatestSubscriber.module.exports.__webpack_modules__.59130.CombineLatestSubscriber.notifyNext (/lc/index.js:199178:34)
      at InnerSubscriber.module.exports.__webpack_modules__.77806.InnerSubscriber._next (/lc/index.js:197393:21) {
    details: {
      tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
      partner: '0x54B394C28B9e96628471fdecEBF1077a67f70B93'
    }
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    partner: '0x54B394C28B9e96628471fdecEBF1077a67f70B93'
  },
  error: true
}
(node:37) UnhandledPromiseRejectionWarning: RaidenError: No open channel has been found.
    at MergeMapSubscriber.project (/lc/index.js:239088:105)
    at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:203385:27)
    at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:203375:18)
    at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198144:18)
    at ThrowIfEmptySubscriber.module.exports.__webpack_modules__.31878.ThrowIfEmptySubscriber._next (/lc/index.js:206073:26)
    at ThrowIfEmptySubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198144:18)
    at TakeSubscriber.module.exports.__webpack_modules__.23260.TakeSubscriber._next (/lc/index.js:205487:30)
    at TakeSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198144:18)
    at CombineLatestSubscriber.module.exports.__webpack_modules__.59130.CombineLatestSubscriber.notifyNext (/lc/index.js:199178:34)
    at InnerSubscriber.module.exports.__webpack_modules__.77806.InnerSubscriber._next (/lc/index.js:197393:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Logs:
[Archive.zip](https://github.com/raiden-network/light-client/files/5584006/Archive.zip)

**Comment by palango** [comment]
A similar error occurred tonight:
```
{
    "result": "scenario error",
    "message": "HTTP status code \"500\" while fetching http://127.0.0.1:41269/api/v1/channels.
     Expected 201: <!DOCTYPE html>
     <html lang=\"en\">
     <head>
     <meta charset=\"utf-8\">
     <title>Error</title>
     </head>
     <body>
     <pre>InternalServerError: timeout (requestBody=&quot;{"method":"eth_sendRawTransaction","params":["0xf8c9808449504f808301907a943ea2a1fed7fdef300da19e97092ce8fdf8bf66a380b8640a798f240000000000000000000000002c2eba1734911c0fc58f2c032ca0d99dd98d8c2000000000000000000000000014b8808547bf00a9b522b9e6855f0cce01735b1100000000000000000000000000000000000000000000000000000000000000282da0b236c07df687e6e82bab60507ef40df2b93a663483a11fe3f4fab8c05f844bbca04632ce216cb649cf8afe0aa7af232ce6acc67816142c941a5c1f06205b5f6915"],"id":613,"jsonrpc":"2.0"}&quot;, requestMethod=&quot;POST&quot;, timeout=120000, url=&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;, code=TIMEOUT, version=web/5.0.10)
    at Object.internalErrorHandler (/lc/index.js:254987:31)
    at Layer.handle_error (/lc/index.js:56941:5)
    at trim_prefix (/lc/index.js:56515:13)
    at /lc/index.js:56484:7
    at Function.process_params (/lc/index.js:56535:12)
    at next (/lc/index.js:56475:10)
    at Layer.handle_error (/lc/index.js:56937:12)
    at trim_prefix (/lc/index.js:56515:13)
    at /lc/index.js:56484:7
    at Function.process_params (/lc/index.js:56535:12)</pre>
    </body>
    </html>
    ",
    "event": "Run finished",
    "logger": "scenario_player.main", 
    level": "error",
    "timestamp": "2020-11-24 01:01:48.566787"
```

**Comment by christianbrb** [comment]
Seems to be an infrastructure issue

Maybe add them to the retryable errors.

Also see #2402 and #2404

**Comment by andrevmatos** [comment]
I'm creating a PR to refactor some things about our error handlers, including handling these `timeout` errors upon reaching the geth node, but it'd be better to check if there's anything wrong with it on the infrastructure side (cc @ulope)

**Comment by ulope** [comment]
Looking at the geth node logs for the 2020-11-24 01:00  time range there are a whole bunch of `replacement transaction underpriced` errors in response to `eth_sendRawTransaction` calls. Not sure if that's relevant to this issue.

Other than that the log looks normal.

```
geth_1  | INFO [11-24|01:00:02.194] Submitted transaction                    fullhash=0x8be476ce321dc6020792b1bb977abc58ed1bfa1f541937168cd99e023147986e recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:00:12.090] Imported new chain segment               blocks=1     txs=4    mgas=0.854    elapsed=13.149ms    mgasps=64.985   number=3807148      hash="838bda…937b57" dirty=255.92MiB
geth_1  | INFO [11-24|01:00:13.740] Setting new local account                address=0x08f6039fb51314FEeeAe69d359735ceB694C9E58
geth_1  | INFO [11-24|01:00:13.741] Submitted transaction                    fullhash=0x36a596fa5023a7bdef9ab6f10fac06d29ac4404166ebc73cfff190caa690eb9e recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:00:13.749] Setting new local account                address=0x0Ae10A091D2BE76829549C0aAf6f6C828f1F1F92
geth_1  | INFO [11-24|01:00:13.750] Submitted transaction                    fullhash=0xe718a3504516bddc562da7cffe31f4462f54c6f4b8653eb03275c764ede688c3 recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | WARN [11-24|01:00:13.773] Served eth_sendRawTransaction            conn=10.104.7.12:55962 reqid=630  t="524.157µs"   err="replacement transaction underpriced"
geth_1  | INFO [11-24|01:00:13.803] Setting new local account                address=0x4C56376B49Fc1e627D710d665D202B05F86CB0E1
geth_1  | INFO [11-24|01:00:13.804] Submitted transaction                    fullhash=0xf8690ca4f9a951ae56e1f4a5817265934bd14253d8d4e0d0ba00dbbd529d8416 recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | WARN [11-24|01:00:13.805] Served eth_sendRawTransaction            conn=10.104.7.12:55974 reqid=635  t=2.30281ms     err="replacement transaction underpriced"
geth_1  | WARN [11-24|01:00:13.819] Served eth_sendRawTransaction            conn=10.104.7.12:55980 reqid=631  t="613.312µs"   err="replacement transaction underpriced"
geth_1  | WARN [11-24|01:00:13.837] Served eth_sendRawTransaction            conn=10.104.7.12:55982 reqid=638  t="513.596µs"   err="replacement transaction underpriced"
geth_1  | INFO [11-24|01:00:16.049] Imported new chain segment               blocks=1     txs=1    mgas=0.023    elapsed=1.182ms     mgasps=19.273   number=3807148      hash="38f980…6d99e3" dirty=255.93MiB
geth_1  | INFO [11-24|01:00:18.900] Submitted transaction                    fullhash=0x0d18db33a4b6fa5c7b9f7b4da39378fe879f18a695ef62ba98265cf96f382c36 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:00:18.987] Submitted transaction                    fullhash=0x59093047387a683d7f900cde4f0a1e312729af85edca8af684caafe0dda1b4d0 recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:00:18.990] Submitted transaction                    fullhash=0x68cd9c97ce437baa6ddf8955a16206b4597412d9eff9477d40dab8d0e9abdb35 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | WARN [11-24|01:00:19.007] Served eth_sendRawTransaction            conn=10.104.7.12:56252 reqid=676  t="939.782µs"   err="replacement transaction underpriced"
geth_1  | INFO [11-24|01:00:22.687] Deep froze chain segment                 blocks=4     elapsed=538.519ms   number=3717148      hash="2ac856…4a143a"
geth_1  | INFO [11-24|01:00:24.110] Submitted transaction                    fullhash=0x5c22c16a43cbd90593e9a34a6b3a17be60c57b1d2f47ceda0c8b1b2d3879f841 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:00:27.365] Imported new chain segment               blocks=1     txs=15   mgas=1.818    elapsed=35.001ms    mgasps=51.952   number=3807149      hash="049803…a3afbb" dirty=255.88MiB
geth_1  | INFO [11-24|01:00:30.482] Chain reorg detected                     number=3807148      hash="838bda…937b57" drop=1 dropfrom="049803…a3afbb" add=1 addfrom="66fef5…fa1fe9"
geth_1  | INFO [11-24|01:00:30.483] Imported new chain segment               blocks=1     txs=6    mgas=5.778    elapsed=214.456ms   mgasps=26.944   number=3807149      hash="66fef5…fa1fe9" dirty=255.90MiB
geth_1  | INFO [11-24|01:00:40.496] Imported new chain segment               blocks=1     txs=1    mgas=0.023    elapsed="891.486µs" mgasps=25.570   number=3807148      hash="44f7ea…43a0ef" dirty=255.90MiB
geth_1  | INFO [11-24|01:00:42.223] Imported new chain segment               blocks=1     txs=13   mgas=0.873    elapsed=14.217ms    mgasps=61.424   number=3807150      hash="d85182…ff872d" dirty=255.64MiB
geth_1  | INFO [11-24|01:00:45.485] Imported new chain segment               blocks=1     txs=6    mgas=0.406    elapsed=7.720ms     mgasps=52.541   number=3807150      hash="6e9278…038c2e" dirty=255.67MiB
geth_1  | INFO [11-24|01:00:46.152] Imported new chain segment               blocks=1     txs=5    mgas=4.856    elapsed=26.791ms    mgasps=181.252  number=3807150      hash="d604d9…69ddd8" dirty=255.68MiB
geth_1  | INFO [11-24|01:00:46.358] Imported new chain segment               blocks=1     txs=2    mgas=4.704    elapsed=28.758ms    mgasps=163.580  number=3807150      hash="e045b0…44dc86" dirty=255.68MiB
geth_1  | INFO [11-24|01:00:46.602] Imported new chain segment               blocks=1     txs=12   mgas=6.266    elapsed=29.898ms    mgasps=209.576  number=3807149      hash="fcf4d8…4f63e1" dirty=255.71MiB
geth_1  | INFO [11-24|01:00:58.494] Imported new chain segment               blocks=1     txs=8    mgas=0.517    elapsed=13.955ms    mgasps=37.052   number=3807151      hash="860d65…b431f8" dirty=255.65MiB
geth_1  | INFO [11-24|01:01:12.130] Imported new chain segment               blocks=1     txs=0    mgas=0.000    elapsed=1.276ms     mgasps=0.000    number=3807152      hash="157333…1eb530" dirty=255.61MiB
geth_1  | INFO [11-24|01:01:22.824] Deep froze chain segment                 blocks=4     elapsed=136.188ms   number=3717152      hash="34db29…18f25a"
geth_1  | INFO [11-24|01:01:27.347] Imported new chain segment               blocks=1     txs=1    mgas=0.021    elapsed=5.987ms     mgasps=3.508    number=3807153      hash="5fefed…9a3987" dirty=255.42MiB
geth_1  | INFO [11-24|01:01:42.810] Imported new chain segment               blocks=1     txs=3    mgas=0.350    elapsed=7.865ms     mgasps=44.499   number=3807154      hash="143f8a…e4f28c" dirty=255.35MiB
geth_1  | INFO [11-24|01:01:42.816] Imported new chain segment               blocks=1     txs=4    mgas=0.371    elapsed=5.983ms     mgasps=62.013   number=3807154      hash="8a8d59…03d84e" dirty=255.36MiB
geth_1  | INFO [11-24|01:01:46.053] Imported new chain segment               blocks=1     txs=4    mgas=0.373    elapsed=4.721ms     mgasps=78.961   number=3807154      hash="ba4147…cd3606" dirty=255.37MiB
geth_1  | INFO [11-24|01:01:57.159] Imported new chain segment               blocks=1     txs=3    mgas=0.730    elapsed=9.860ms     mgasps=74.021   number=3807155      hash="754723…7c0b03" dirty=255.39MiB
geth_1  | INFO [11-24|01:02:00.074] Imported new chain segment               blocks=1     txs=3    mgas=0.188    elapsed=3.682ms     mgasps=51.181   number=3807155      hash="f3310c…4d38f9" dirty=255.39MiB
geth_1  | INFO [11-24|01:02:00.124] Imported new chain segment               blocks=1     txs=2    mgas=0.044    elapsed=1.655ms     mgasps=26.464   number=3807155      hash="7bb94e…a3a6ea" dirty=255.40MiB
geth_1  | INFO [11-24|01:02:00.607] Submitted transaction                    fullhash=0x02bc5fe3e5133a906d786ac5d49a46a61866bb5fbc69757cefd48daca090ba80 recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:02:00.920] Submitted transaction                    fullhash=0xfd46f1e42186664ef7094b122b66a1e39c37da90a94c71fa487ccd60a0aaa339 recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:02:01.258] Submitted transaction                    fullhash=0xfb849fd9bbc4ed4443ddee870f7365947eb348bc45bfcb09657ee70612205cec recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:02:06.229] Submitted transaction                    fullhash=0xf8098e42988adaa4a87d3587d1af53810fac75f829079d1ce073800c0521b769 recipient=0xbe9d81D3fF753f177A8D938bEBc9A0438E10112a
geth_1  | INFO [11-24|01:02:06.943] Submitted transaction                    fullhash=0x35bcd28bf704c0029af011b7f704a0b139915ce5e0b125b14be560de7235413f recipient=0xe70f17A390DAAd8d6646B83aabB4425a5Fcfcd43
geth_1  | INFO [11-24|01:02:07.596] Submitted transaction                    fullhash=0xa07a1d5a6b99ebf7a77b5db9ab210a80a653279f2444902392058d23636c2f6f recipient=0xa32A6De548dff3E30E78F3a58c4C06E1f8CB1629
geth_1  | INFO [11-24|01:02:08.442] Submitted transaction                    fullhash=0xe7efd95effc8c8ec5d10c3ece1825982d683d31778f993353d8ac5c92cac3a80 recipient=0x0025693aCe654892047297F1DD272BE7bCe17f45
geth_1  | INFO [11-24|01:02:09.181] Submitted transaction                    fullhash=0xb4a3bc6e1cbc9b0aaf389114588ccafdaa338aeff51ecf0e0b69c1e0f76ac500 recipient=0x4C4ACbD2690744033fC4f0bb233aA5100aAeBB55
geth_1  | INFO [11-24|01:02:09.681] Submitted transaction                    fullhash=0x1119719d5a4fada469c6cedde5fb27be99653c7eecbe81487404bca700f8f285 recipient=0x1fdbDdb7C338Ec8AE74aF7951eB4c71186062cdC
geth_1  | INFO [11-24|01:02:10.310] Submitted transaction                    fullhash=0xe96ee33e4629a39741af6649acfe04dd98287cce62a9d8edb047c0e17b5e8c89 recipient=0xAb7C9793E51198B5e36C924E71C64a7F4189bee2
geth_1  | INFO [11-24|01:02:11.118] Submitted transaction                    fullhash=0xd39f5705e93c8efc4a5d8365d536e5885abd5d5fd64494656fdcedd5419e542f recipient=0xD8Bbcc643a632Bb6E47a26ec5Cef8288731b3b48
geth_1  | INFO [11-24|01:02:11.909] Submitted transaction                    fullhash=0x5f67700dd41401f5dcea7ccdaf7aa9ac2d4c1148365a024654a652b5b49772b3 recipient=0x23DA783fA762bEBEd1f5aA276c778FCE989E1Bcc
geth_1  | INFO [11-24|01:02:12.229] Imported new chain segment               blocks=1     txs=17   mgas=1.107    elapsed=16.629ms    mgasps=66.546   number=3807156      hash="7146c5…277b3b" dirty=255.40MiB
geth_1  | INFO [11-24|01:02:12.413] Submitted transaction                    fullhash=0x9971756ba3e9e397ce61849c30a444172ea87cb6e8ca24bc6fa3b290e5e3e50d recipient=0xD7E17af37c92032E7e16494322786942066902aA
geth_1  | INFO [11-24|01:02:14.560] Chain reorg detected                     number=3807155      hash="754723…7c0b03" drop=1 dropfrom="7146c5…277b3b" add=1 addfrom="15620b…f5b3ce"
geth_1  | INFO [11-24|01:02:14.562] Imported new chain segment               blocks=1     txs=4    mgas=0.321    elapsed=6.555ms     mgasps=48.980   number=3807156      hash="15620b…f5b3ce" dirty=255.41MiB
geth_1  | INFO [11-24|01:02:14.972] Imported new chain segment               blocks=1     txs=1    mgas=0.023    elapsed=1.087ms     mgasps=20.967   number=3807156      hash="6a7ff9…18fe1a" dirty=255.41MiB
geth_1  | INFO [11-24|01:02:23.009] Deep froze chain segment                 blocks=4     elapsed=184.645ms   number=3717156      hash="706d2f…cf1225"
geth_1  | INFO [11-24|01:02:27.250] Imported new chain segment               blocks=1     txs=18   mgas=1.298    elapsed=19.847ms    mgasps=65.413   number=3807157      hash="d4a099…59fcd5" dirty=255.33MiB
geth_1  | INFO [11-24|01:02:29.135] Imported new chain segment               blocks=1     txs=3    mgas=0.188    elapsed=4.164ms     mgasps=45.254   number=3807157      hash="2732e3…91c778" dirty=255.33MiB
geth_1  | INFO [11-24|01:02:30.218] Submitted transaction                    fullhash=0x1f5b9c55519245b50f18bcdc2f3a190832855115c07fe1107848b6b96144520b recipient=0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3
geth_1  | INFO [11-24|01:02:30.522] Imported new chain segment               blocks=1     txs=6    mgas=0.769    elapsed=74.248ms    mgasps=10.356   number=3807157      hash="537b15…f19cd8" dirty=255.34MiB
geth_1  | INFO [11-24|01:02:34.548] Submitted transaction                    fullhash=0x899adb27c4cd3e7c29e4cf7d44e94bec29bccbe339d35717352f0a53bdc61f93 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:34.866] Submitted transaction                    fullhash=0x229d1015c00d3c81a523a3e613445173ac5c4bc2e24f3c638b57bdb6a28c897e recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.078] Submitted transaction                    fullhash=0xf7aa785881eb09a9e3540f4f901dc252211c8e99de46661f959c4a64d7c3fdc2 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.210] Submitted transaction                    fullhash=0x2f406d45ba9c291622081e18140b757ce56752d95cf543ae8d52d5a415929559 recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:35.344] Submitted transaction                    fullhash=0xa2fbb2d6127c8da5ff38b119ac6a6a7c3ed8bed80e414a5c2d886e425a53933e recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.491] Submitted transaction                    fullhash=0x0681f8c79f51c586ffc0ebb14402885a4c36c3cbdb2e3b9cc1e809c5bd7861b2 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.624] Submitted transaction                    fullhash=0x35abc98781ac8e2a80f9f070c92477840d7319bedfeb03865867d26db788dc86 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.687] Submitted transaction                    fullhash=0x597c1e40c37270c51c022c8d29ebcf2bd86727be5ffa9667a6a2886af1ac92dd recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:35.732] Submitted transaction                    fullhash=0x323c569d11b35422f326e7b0e4190fe49be88f167e6fe991461039dd9fceefcb recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.787] Submitted transaction                    fullhash=0x91619efe35a480897f11595e12895f5698ed13562b508980e864b5609915019c recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:35.863] Submitted transaction                    fullhash=0x9fa4122ec0f56dd0b1c663fc8773f178a41a8bf2e91c6fcb1ad2e0f0c1fe4a33 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:35.916] Submitted transaction                    fullhash=0x661ca9b0bd7b2adfd3f9fb4ee71eea2adb77e5edd997135d6829b13c31c0cb8a recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:35.991] Submitted transaction                    fullhash=0xf10896b1c11ccfc9f90a310db8e3c91d8bd73965c6fcc6288bffd88889359474 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:36.020] Submitted transaction                    fullhash=0x46ed9b4632a8a070eb0fefca299564000c829a5b0593610301d7a27d68775415 recipient=0x59105441977ecD9d805A4f5b060E34676F50F806
geth_1  | INFO [11-24|01:02:36.079] Submitted transaction                    fullhash=0x8b2bd89be1757a29b953e89f71159c60b168fd725cf15d35408f1b1a84ba8dd5 recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:36.111] Submitted transaction                    fullhash=0x00f03403b73caf3ecac836b04c60cffd99a857fe0bdeda62159bd9a50a719ab2 recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:36.144] Submitted transaction                    fullhash=0x06df7a788900be32507368f70c58bfde78b5c29595c3928244f1186e941cd78f recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:36.171] Submitted transaction                    fullhash=0x498ee396c61ae3c774ef324ba6bd6032b9d1f64392861495192bb6f57b0d956a recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:36.203] Submitted transaction                    fullhash=0x55b606a8c2167b5b52fe8bd2daf85c21ab330f010ec326fa50f7218e04c912c3 recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:36.235] Submitted transaction                    fullhash=0x4132230a8b72280540e7671b132aefb29f65ee20074c839d43f0b08e9d61f59e recipient=0x0794F09913AA8C77C8c5bdd1Ec4Bb51759Ee0cC5
geth_1  | INFO [11-24|01:02:42.494] Imported new chain segment               blocks=1     txs=5    mgas=0.435    elapsed=360.679ms   mgasps=1.207    number=3807158      hash="e3be57…a0e1b1" dirty=255.37MiB
geth_1  | INFO [11-24|01:02:44.545] Imported new chain segment               blocks=1     txs=3    mgas=0.364    elapsed=45.884ms    mgasps=7.936    number=3807158      hash="2dba77…c71889" dirty=255.38MiB
geth_1  | INFO [11-24|01:02:58.025] Imported new chain segment               blocks=1     txs=0    mgas=0.000    elapsed=549.764ms   mgasps=0.000    number=3807159      hash="769bfb…90d6db" dirty=254.98MiB
geth_1  | INFO [11-24|01:02:58.450] Chain reorg detected                     number=3807158      hash="e3be57…a0e1b1" drop=1 dropfrom="769bfb…90d6db" add=1 addfrom="93c854…2b5763"
geth_1  | INFO [11-24|01:02:58.450] Imported new chain segment               blocks=1     txs=3    mgas=0.127    elapsed=12.599ms    mgasps=10.069   number=3807159      hash="93c854…2b5763" dirty=254.99MiB
```

**Comment by andrevmatos** [comment]
Thank you, @ulope , for looking into it. `replacement transaction underpriced` is expected, that's how we deal with concurrent txs, handling and retrying (allow us to work reliably without the need to keep `nonce` locally or incurring in the risk of it getting out of sync, as well as not requiring exclusive access to the account). Not sure anything there qualify as root cause of these timeouts, maybe just network hiccups, let's hope the retry will make this kind of issue not affect us.

**Comment by ulope** [comment]
Not related to this issue but

> replacement transaction underpriced is expected, that's how we deal with concurrent txs, handling and retrying (allow us to work reliably without the need to keep nonce locally or incurring in the risk of it getting out of sync, as well as not requiring exclusive access to the account). 

How do you make sure that you don't accidentally clobber an unrelated earlier tx if the gas price has increased in the meantime?
