### ISSUE TITLE
BF4 gets Internal error in the eth_sendRawTransaction call

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2394]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
```
{
  "task": "<OpenChannelTask: {'from': 4, 'to': 5, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-11-24 00:58:14.801422",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 58, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:41269/api/v1/channels. Expected 201: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: timeout (requestBody=&quot;{\\&quot;method\\&quot;:\\&quot;eth_sendRawTransaction\\&quot;,\\&quot;params\\&quot;:[\\&quot;0xf8c9808449504f808301907a943ea2a1fed7fdef300da19e97092ce8fdf8bf66a380b8640a798f240000000000000000000000002c2eba1734911c0fc58f2c032ca0d99dd98d8c2000000000000000000000000014b8808547bf00a9b522b9e6855f0cce01735b1100000000000000000000000000000000000000000000000000000000000000282da0b236c07df687e6e82bab60507ef40df2b93a663483a11fe3f4fab8c05f844bbca04632ce216cb649cf8afe0aa7af232ce6acc67816142c941a5c1f06205b5f6915\\&quot;],\\&quot;id\\&quot;:613,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;, requestMethod=&quot;POST&quot;, timeout=120000, url=&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;, code=TIMEOUT, version=web/5.0.10)<br> &nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:254987:31)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56941:5)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> &nbsp; &nbsp;at /lc/index.js:56484:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)<br> &nbsp; &nbsp;at next (/lc/index.js:56475:10)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56937:12)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> &nbsp; &nbsp;at /lc/index.js:56484:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)</pre>\n</body>\n</html>\n"
}
```

Fails at:
**from: 4, to: 5, total_deposit: 1_000_000_000_000_000_000, expected_http_status: 201**

```
<!DOCTYPE html>\n
<html lang=\"en\">\n
<head>\n
	<meta charset=\"utf-8\">\n
	<title>Error</title>\n
	</head>\n
	<body>\n
		<pre>InternalServerError: timeout (requestBody=&quot;{\\&quot;method\\&quot;:\\&quot;eth_sendRawTransaction\\&quot;,\\&quot;params\\&quot;:[\\&quot;0xf8c9808449504f808301907a943ea2a1fed7fdef300da19e97092ce8fdf8bf66a380b8640a798f240000000000000000000000002c2eba1734911c0fc58f2c032ca0d99dd98d8c2000000000000000000000000014b8808547bf00a9b522b9e6855f0cce01735b1100000000000000000000000000000000000000000000000000000000000000282da0b236c07df687e6e82bab60507ef40df2b93a663483a11fe3f4fab8c05f844bbca04632ce216cb649cf8afe0aa7af232ce6acc67816142c941a5c1f06205b5f6915\\&quot;],\\&quot;id\\&quot;:613,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;, requestMethod=&quot;POST&quot;, timeout=120000, url=&quot;http://geth.goerli.ethnodes.brainbot.com:8545&quot;, code=TIMEOUT, version=web/5.0.10)<br> 
			&nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:254987:31)<br> 
			&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56941:5)<br> 
			&nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> 
			&nbsp; &nbsp;at /lc/index.js:56484:7<br> 
			&nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)<br> 
			&nbsp; &nbsp;at next (/lc/index.js:56475:10)<br> 
			&nbsp; &nbsp;at Layer.handle_error (/lc/index.js:56937:12)<br> 
			&nbsp; &nbsp;at trim_prefix (/lc/index.js:56515:13)<br> 
			&nbsp; &nbsp;at /lc/index.js:56484:7<br> 
			&nbsp; &nbsp;at Function.process_params (/lc/index.js:56535:12)
		</pre>\n
	</body>\n
	</html>
```

Scenario log:
[scenario-player-run_bf4_multi_payments_same_node_2020-11-24T00:53:40.log](https://github.com/raiden-network/light-client/files/5589863/scenario-player-run_bf4_multi_payments_same_node_2020-11-24T00.53.40.log)

**Comment by christianbrb** [comment]
Same as #2388
