### ISSUE TITLE
BF6 gets Remote end closed connection without response

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2403]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
-
One of the nodes raiden api's error with

```
http.client.RemoteDisconnected: Remote end closed connection without response
```
 
```
{
  "task": "<OpenChannelTask: {'from': 4, 'to': 0, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-11-25 01:22:45.613601",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse\n    response.begin()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 279, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send\n    timeout=timeout\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 641, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py\", line 368, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py\", line 685, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse\n    response.begin()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 279, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nurllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 48, in _run\n    timeout=self._timeout,\n  File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 55, in _run\n    ) from ex\nscenario_player.exceptions.RESTAPIError: Error performing REST-API call: open_channel"
}
```

Fails at:

```
OpenChannelTask: {'from': 4, 'to': 0, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}
```

Error:
```
Traceback (most recent call last):\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen\n    chunked=chunked)
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    six.raise_from(e, None)\n  
File \"<string>\", line 2, in raise_from
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  
File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse\n    
response.begin()\n  
File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin\n    
version, status, reason = self._read_status()\n  
File \"/usr/local/lib/python3.7/http/client.py\", line 279, in _read_status\n    
raise RemoteDisconnected(\"Remote end closed connection without\"\n
http.client.RemoteDisconnected: Remote end closed connection without response\n\n

During handling of the above exception, another exception occurred:\n\n

Traceback (most recent call last):\n  
File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send\n    
timeout=timeout\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 641, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py\", line 368, in increment\n    
raise six.reraise(type(error), error, _stacktrace)\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py\", line 685, in reraise\n    
raise value.with_traceback(tb)\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen\n    chunked=chunked)\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    six.raise_from(e, None)\n  
File \"<string>\", line 2, in raise_from\n  
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  
File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse\n    
response.begin()\n  
File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin\n    
version, status, reason = self._read_status()\n  
File \"/usr/local/lib/python3.7/http/client.py\", line 279, in _read_status\n    
raise RemoteDisconnected(\"Remote end closed connection without\"\n
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\n
During handling of the above exception, another exception occurred:\n\n
Traceback (most recent call last):\n  
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 48, in _run\n    timeout=self._timeout,\n  
File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 542, in request\n    
resp = self.send(prep, **send_kwargs)\n  
File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 655, in send\n    
r = adapter.send(request, **kwargs)\n  
File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 498, in send\n    
raise ConnectionError(err, request=request)\n
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\n
The above exception was the direct cause of the following exception:\n\n
Traceback (most recent call last):\n  
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    
return_val = self._run(*args, **kwargs)\n  
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 55, in _run\n    
) from ex\n
scenario_player.exceptions.RESTAPIError: Error performing REST-API call: open_channel"
```

[scenario-player-run_bf6_stress_hub_node_2020-11-25T00:19:24.log](https://github.com/raiden-network/light-client/files/5596496/scenario-player-run_bf6_stress_hub_node_2020-11-25T00.19.24.log)

**Comment by christianbrb** [comment]
@agatsoh Please attach the *.log from the nodes

**Comment by agatsoh** [comment]
Entire logs of node0 and node4

[bf6_node0_node4_logs.tar.gz](https://github.com/raiden-network/light-client/files/5601231/bf6_node0_node4_logs.tar.gz)

**Comment by agatsoh** [comment]
Today encountered a similar error in PFS7 and after analysing the node logs this issue also seems like an infrastructure issue related to this https://github.com/raiden-network/light-client/issues/2388 

Task errors at 

```
OpenChannelTask: {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}
```

recurring error on the node 2 is this 

```
(node:28) UnhandledPromiseRejectionWarning: Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":740,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="http://geth.goerli.ethnodes.brainbot.com:8545", code=TIMEOUT, version=web/5.0.11)
    at Logger.makeError (/lc/index.js:7514:21)
    at Timeout._onTimeout (/lc/index.js:19009:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Scenario log:

[scenario-player-run_pfs7_multiple_payments_2020-11-27T01:18:29.log](https://github.com/raiden-network/light-client/files/5606745/scenario-player-run_pfs7_multiple_payments_2020-11-27T01.18.29.log)


Node logs of node2 and node3
[pfs7_node2_node3_27thNov2020.tar.gz](https://github.com/raiden-network/light-client/files/5606744/pfs7_node2_node3_27thNov2020.tar.gz)

**Comment by andrevmatos** [comment]
Ok, this is weird.. on the BF6 logs, the node004 was first doing successful requests but then suddenly started getting these `timeout`s, and didn't recover until getting stopped (which led to the issue), even though we retried them, but the funny thing is that both it and node000 were using `geth` at the same time, but node000 did not get these timeouts!
The only reasons I can think goes in these lines: Either
- `ethers` got in some weird unrecoverable state, possibly because of one timeout, but then reused this exception for some reason
- `geth` is somehow selectively blacklisting some client, maybe due to some burst of requests, but since these were on docker, they would be running in the same IP, so the blacklist shouldn't be by IP, not sure how else could it be
- the SP docker environment somehow got unstable, maybe hitting some FD limit or whatever?

Notice only 1st reason could be caused by our code (in this case, a dependency), the other 2 are infrastructure issues. I've tried reproducing both locally, and couldn't, which points towards it not being a code issue, but I'll try some more.. anyway, this seems to be very specific to scenarios, and not something one could witness on "real life", but surely we need to get those greens.

**Comment by agatsoh** [comment]
Encountered this issue today as well on PFS7

[scenario-player-run_pfs7_multiple_payments_2020-12-01T00:41:09.log](https://github.com/raiden-network/light-client/files/5621707/scenario-player-run_pfs7_multiple_payments_2020-12-01T00.41.09.log)

node logs 
[pfs7_node3_node4_01Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5621765/pfs7_node3_node4_01Dec2020.tar.gz)

**Comment by agatsoh** [comment]
Encountered this today on BF6
[scenario-player-run_bf6_stress_hub_node_2020-12-02T01:01:17.log](https://github.com/raiden-network/light-client/files/5628668/scenario-player-run_bf6_stress_hub_node_2020-12-02T01.01.17.log)


[bf6_node8_node0_2ndDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5628671/bf6_node8_node0_2ndDec2020.tar.gz)
