### ISSUE TITLE
BF7 gets Error: Failed to set ICE candidate. Error: missing response eth_blockNumber

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2425]
## Expected Result
- 

## Actual Result
- 

Recurring error on node0
**Failed to set ICE candidate.**
```
2020-12-02T02:53:53.221Z [warn] RTC: error setting candidate, ignoring 0x2FBDD2E6b59bF7970fA02C7feA108F50873ED283|0x51932ab7bE458A15476f63F1bBe724d94064Ce3e new [Object: null prototype] {
  candidate: 'candidate:4112619227 1 udp 2122260223 172.17.0.2 38788 typ host generation 0 ufrag HvKW network-id 1',
  sdpMid: '0',
  sdpMLineIndex: 0,
  foundation: '4112619227',
  component: 'rtp',
  priority: 2122260223,
  address: '172.17.0.2',
  protocol: 'udp',
  port: 38788,
  type: 'host',
  tcpType: null,
  relatedAddress: null,
  relatedPort: null,
  usernameFragment: 'HvKW'
} [Error: Failed to set ICE candidate.]
```

Then it gives 
**Couldn't set up WebRTC dataChannel, retrying**
```
2020-12-02T02:53:59.962Z [info] Couldn't set up WebRTC dataChannel, retrying 0x2FBDD2E6b59bF7970fA02C7feA108F50873ED283|0xaE1a4825F3E1205c3853BBBF3094Bc03BBc3D253 RTC: connection failed
2020-12-02T02:54:00.087Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'rtc/channel',
  payload: undefined,
  meta: { address: '0xaE1a4825F3E1205c3853BBBF3094Bc03BBc3D253' }
}
```
Though webrtc channel failed to establish it does not stop the client.

Finally we have 
**Error: missing response** for `eth_blockNumber` this would mostly be related to the infrastructure problems that we are seeing
```
(node:12) UnhandledPromiseRejectionWarning: Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":4576,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"code":"ECONNRESET"}, url="http://geth.goerli.ethnodes.brainbot.com:8545", code=SERVER_ERROR, version=web/5.0.11)
    at Logger.makeError (/lc/index.js:7514:21)
    at Logger.throwError (/lc/index.js:7523:20)
    at /lc/index.js:19073:36
    at step (/lc/index.js:18894:23)
    at Object.throw (/lc/index.js:18875:53)
    at rejected (/lc/index.js:18867:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```
Scenario log

[scenario-player-run_bf7_long_path_2020-12-02T02:03:33.log](https://github.com/raiden-network/light-client/files/5628977/scenario-player-run_bf7_long_path_2020-12-02T02.03.33.log)

node logs
[bf7_node0_node1_02Dec2020.tar.gz](https://github.com/raiden-network/light-client/files/5628979/bf7_node0_node1_02Dec2020.tar.gz)

**Comment by andrevmatos** [comment]
The `addIceCandidate` error is just a warning, it's normal on WebRTC connections; the `eth_blockNumber` error though was the cause of this issue, and got solved also by #2417
