### ISSUE TITLE
PFS7 node0 gets timeout for eth_blockNumber call

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2438]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
Same exception as I have mentioned in this issue
https://github.com/raiden-network/light-client/issues/2403#issuecomment-734711855

```
{
  "task": "<OpenChannelTask: {'from': 0, 'to': 4, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-12-08 02:17:57.509138",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 387, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse\n    response.begin()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/local/lib/python3.7/http/client.py\", line 271, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/local/lib/python3.7/socket.py\", line 589, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/local/lib/python3.7/site-packages/gevent/_socket3.py\", line 509, in recv_into\n    self._wait(self._read_event)\n  File \"src/gevent/_hub_primitives.py\", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket\n  File \"src/gevent/_hub_primitives.py\", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket\n  File \"src/gevent/_hub_primitives.py\", line 313, in gevent._gevent_c_hub_primitives._primitive_wait\n  File \"src/gevent/_hub_primitives.py\", line 314, in gevent._gevent_c_hub_primitives._primitive_wait\n  File \"src/gevent/_hub_primitives.py\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\n  File \"src/gevent/_hub_primitives.py\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\n  File \"src/gevent/_hub_primitives.py\", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\n  File \"src/gevent/_waiter.py\", line 151, in gevent._gevent_c_waiter.Waiter.get\n  File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n  File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n  File \"src/gevent/_greenlet_primitives.py\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\n  File \"src/gevent/_gevent_c_greenlet_primitives.pxd\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send\n    timeout=timeout\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 641, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py\", line 368, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py\", line 686, in reraise\n    raise value\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen\n    chunked=chunked)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 389, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 307, in _raise_timeout\n    raise ReadTimeoutError(self, url, \"Read timed out. (read timeout=%s)\" % timeout_value)\nurllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=33875): Read timed out. (read timeout=1800)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 49, in _run\n    timeout=self._timeout,\n  File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 529, in send\n    raise ReadTimeout(e, request=request)\nrequests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=33875): Read timed out. (read timeout=1800)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 52, in _run\n    self._handle_timeout(ex)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/raiden_api.py\", line 14, in _handle_timeout\n    ) from ex\nscenario_player.exceptions.TransferFailed: Open Channel didn't complete within timeout of 1800"
}
```

Fails at:
`OpenChannelTask: {'from': 0, 'to': 4, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}`

```
Traceback (most recent call last):
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 387, in _make_request
six.raise_from(e, None)
File \"<string>\", line 2, in raise_from
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 383, in _make_request
httplib_response = conn.getresponse()
File \"/usr/local/lib/python3.7/http/client.py\", line 1369, in getresponse
response.begin()
File \"/usr/local/lib/python3.7/http/client.py\", line 310, in begin
version, status, reason = self._read_status()
File \"/usr/local/lib/python3.7/http/client.py\", line 271, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")
File \"/usr/local/lib/python3.7/socket.py\", line 589, in readinto
return self._sock.recv_into(b)
File \"/usr/local/lib/python3.7/site-packages/gevent/_socket3.py\", line 509, in recv_into
self._wait(self._read_event)
File \"src/gevent/_hub_primitives.py\", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
File \"src/gevent/_hub_primitives.py\", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
File \"src/gevent/_hub_primitives.py\", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
File \"src/gevent/_hub_primitives.py\", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
File \"src/gevent/_hub_primitives.py\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File \"src/gevent/_hub_primitives.py\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File \"src/gevent/_hub_primitives.py\", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
File \"src/gevent/_waiter.py\", line 151, in gevent._gevent_c_waiter.Waiter.get
File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File \"src/gevent/_greenlet_primitives.py\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File \"src/gevent/_greenlet_primitives.py\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
File \"src/gevent/_gevent_c_greenlet_primitives.pxd\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 449, in send
timeout=timeout
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 641, in urlopen
_stacktrace=sys.exc_info()[2])
File \"/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py\", line 368, in increment
raise six.reraise(type(error), error, _stacktrace)
File \"/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py\", line 686, in reraise
raise value
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 603, in urlopen
chunked=chunked)
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 389, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File \"/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py\", line 307, in _raise_timeout
raise ReadTimeoutError(self, url, \"Read timed out. (read timeout=%s)\" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=33875): Read timed out. (read timeout=1800)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 49, in _run
timeout=self._timeout,
File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 542, in request
resp = self.send(prep, **send_kwargs)
File \"/usr/local/lib/python3.7/site-packages/requests/sessions.py\", line 655, in send
r = adapter.send(request, **kwargs)
File \"/usr/local/lib/python3.7/site-packages/requests/adapters.py\", line 529, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=33875): Read timed out. (read timeout=1800)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__
return_val = self._run(*args, **kwargs)
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 52, in _run
self._handle_timeout(ex)
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/raiden_api.py\", line 14, in _handle_timeout
) from ex
scenario_player.exceptions.TransferFailed: Open Channel didn't complete within timeout of 1800

```

**scenario_player.exceptions.TransferFailed: Open Channel didn't complete within timeout of 1800**

Recurring error in node0 logs 

```
(node:12) UnhandledPromiseRejectionWarning: Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":964,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="http://geth.goerli.ethnodes.brainbot.com:8545", code=TIMEOUT, version=web/5.0.11)
    at Logger.makeError (/lc/index.js:7514:21)
    at Timeout._onTimeout (/lc/index.js:19009:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

`Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":964,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="http://geth.goerli.ethnodes.brainbot.com:8545", code=TIMEOUT, version=web/5.0.11)`

[scenario-player-run_pfs7_multiple_payments_2020-12-08T01:45:53.log](https://github.com/raiden-network/light-client/files/5657874/scenario-player-run_pfs7_multiple_payments_2020-12-08T01.45.53.log)

[pfs7_node0_node4_8thDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5657892/pfs7_node0_node4_8thDec2020.tar.gz)

**Comment by taleldayekh** [comment]
Proposal: Try to get an Infura account. @palango

**Comment by christianbrb** [comment]
Did not occur during the last days
