### ISSUE TITLE
PFS8, PFS7 gets transaction gas supplied is too low

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2465]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
```
{
  "task": "<OpenChannelTask: {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "timestamp": "2020-12-27 01:23:42.078839",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"500\" while fetching http://127.0.0.1:41351/api/v1/channels. Expected 201: <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>InternalServerError: processing response error (body=&quot;{\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;,\\&quot;error\\&quot;:{\\&quot;code\\&quot;:-32010,\\&quot;message\\&quot;:\\&quot;Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.\\&quot;},\\&quot;id\\&quot;:1522}\\n&quot;, error={&quot;code&quot;:-32010}, requestBody=&quot;{\\&quot;method\\&quot;:\\&quot;eth_sendRawTransaction\\&quot;,\\&quot;params\\&quot;:[\\&quot;0xf8a4010a82ad4b9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b30000000000000000000000003ea2a1fed7fdef300da19e97092ce8fdf8bf66a3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2da0073c4fb8847de8eaf8b1dbb72ed8ce6f74956b9e5db2d41bfdf60c71146bcfb3a008bb09bc623c476e0a63d66866d4ab4b1e05f68014a6291ea01f901e7e8217e5\\&quot;],\\&quot;id\\&quot;:1522,\\&quot;jsonrpc\\&quot;:\\&quot;2.0\\&quot;}&quot;, requestMethod=&quot;POST&quot;, url=&quot;http://parity.goerli.ethnodes.brainbot.com:8545&quot;, code=SERVER_ERROR, version=web/5.0.11)<br> &nbsp; &nbsp;at Object.internalErrorHandler (/lc/index.js:255578:31)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:57050:5)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56624:13)<br> &nbsp; &nbsp;at /lc/index.js:56593:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56644:12)<br> &nbsp; &nbsp;at next (/lc/index.js:56584:10)<br> &nbsp; &nbsp;at Layer.handle_error (/lc/index.js:57046:12)<br> &nbsp; &nbsp;at trim_prefix (/lc/index.js:56624:13)<br> &nbsp; &nbsp;at /lc/index.js:56593:7<br> &nbsp; &nbsp;at Function.process_params (/lc/index.js:56644:12)</pre>\n</body>\n</html>\n"
}
```

Corressponding exception in node0

```
2020-12-27T01:18:48.375Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'channel/deposit/failure',
  payload: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32010,\"message\":\"Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.\"},\"id\":1522}\n", error={"code":-32010}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8a4010a82ad4b9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b30000000000000000000000003ea2a1fed7fdef300da19e97092ce8fdf8bf66a3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2da0073c4fb8847de8eaf8b1dbb72ed8ce6f74956b9e5db2d41bfdf60c71146bcfb3a008bb09bc623c476e0a63d66866d4ab4b1e05f68014a6291ea01f901e7e8217e5\"],\"id\":1522,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://parity.goerli.ethnodes.brainbot.com:8545", code=SERVER_ERROR, version=web/5.0.11)
      at Logger.makeError (/lc/index.js:7517:21)
      at Logger.throwError (/lc/index.js:7526:20)
      at /lc/index.js:19129:32
      at step (/lc/index.js:18897:23)
      at Object.next (/lc/index.js:18878:53)
      at fulfilled (/lc/index.js:18869:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","error":{"code":-32010,"message":"Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce."},"id":1522}\n',
    error: Error: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.
        at getResult (/lc/index.js:12133:21)
        at processJsonFunc (/lc/index.js:19172:22)
        at /lc/index.js:19104:46
        at step (/lc/index.js:18897:23)
        at Object.next (/lc/index.js:18878:53)
        at fulfilled (/lc/index.js:18869:58)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5) {
      code: -32010,
      data: undefined
    },
    requestBody: '{"method":"eth_sendRawTransaction","params":["0xf8a4010a82ad4b9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b30000000000000000000000003ea2a1fed7fdef300da19e97092ce8fdf8bf66a3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2da0073c4fb8847de8eaf8b1dbb72ed8ce6f74956b9e5db2d41bfdf60c71146bcfb3a008bb09bc623c476e0a63d66866d4ab4b1e05f68014a6291ea01f901e7e8217e5"],"id":1522,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'http://parity.goerli.ethnodes.brainbot.com:8545',
    transaction: {
      nonce: 1,
      gasPrice: BigNumber { _hex: '0x0a', _isBigNumber: true },
      gasLimit: BigNumber { _hex: '0xad4b', _isBigNumber: true },
      to: '0x59105441977ecD9d805A4f5b060E34676F50F806',
      value: BigNumber { _hex: '0x00', _isBigNumber: true },
      data: '0x095ea7b30000000000000000000000003ea2a1fed7fdef300da19e97092ce8fdf8bf66a3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
      chainId: 5,
      v: 45,
      r: '0x073c4fb8847de8eaf8b1dbb72ed8ce6f74956b9e5db2d41bfdf60c71146bcfb3',
      s: '0x08bb09bc623c476e0a63d66866d4ab4b1e05f68014a6291ea01f901e7e8217e5',
      from: '0xbC0ffB83DE6Ee9866b4224879abC1f33D886F843',
      hash: '0x3305ae8e0577820f429b758fd5c05628b07a133eae2f3fe3aee34ff2156bfb29'
    },
    transactionHash: '0x3305ae8e0577820f429b758fd5c05628b07a133eae2f3fe3aee34ff2156bfb29'
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    partner: '0x5EED870De31fe14996C15880Ec16E4b242e4EBcc'
  },
  error: true
}
```

Error statement:
```
{
  "code": -32010,
  "message": "Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce."
}
```

[scenario-player-run_pfs8_mediator_goes_offline_2020-12-27T01:08:34.log](https://github.com/raiden-network/light-client/files/5747502/scenario-player-run_pfs8_mediator_goes_offline_2020-12-27T01.08.34.log)

[pfs8_node0_node1.tar.gz](https://github.com/raiden-network/light-client/files/5747504/pfs8_node0_node1.tar.gz)

**Comment by agatsoh** [comment]
Same exception takes place for PFS7

[scenario-player-run_pfs7_multiple_payments_2020-12-27T00:44:09.log](https://github.com/raiden-network/light-client/files/5747521/scenario-player-run_pfs7_multiple_payments_2020-12-27T00.44.09.log)


[pfs7_node0_node1_28thDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5747523/pfs7_node0_node1_28thDec2020.tar.gz)
