### ISSUE TITLE
Missign error handling in `initMatrixEpic`

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2560]
Got this error while running a scenario today. This should be catched and retried.
```
2021-02-12T10:57:01.650Z [error] Epic error initMatrixEpic [Function: initMatrixEpic] ConnectionError: request failed: getaddrinfo ENOTFOUND transport.transport01.raiden.network
    at /Users/paul/Projects/brainbot/light-client/node_modules/matrix-js-sdk/lib/http-api.js:774:15
    at Request._callback (/Users/paul/Projects/brainbot/light-client/node_modules/matrix-js-sdk/lib/http-api.js:715:9)
    at self.callback (/Users/paul/Projects/brainbot/light-client/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/Users/paul/Projects/brainbot/light-client/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3) {
  _cause: Error: getaddrinfo ENOTFOUND transport.transport01.raiden.network
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'transport.transport01.raiden.network'
  }
}
```

**Comment by taleldayekh** [comment]
Let's wait and see if Matrixless Raiden will happen, if so, close this issue.
