### ISSUE TITLE
MetaMask - RPC Error: InfuraProvider - cannot complete request. All retries exhausted.

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2756]
## Description
In the brave browser I encountered this error. This may not be very serious error. Though I am just making an issue here if we need to look into later if many people start encountering this especially on `mainnet`.

**MetaMask - RPC Error: InfuraProvider - cannot complete request. All retries exhausted.**
Original Error:

```
{
  "code": -32603,
  "message": "Gateway timeout. The request took too long to process. This can happen when querying logs over too wide a block range.",
  "stack": "{\n  \"code\": -32603,\n  \"message\": \"Gateway timeout. The request took too long to process. This can happen when querying logs over too wide a block range.\",\n  \"stack\": \"Error: Gateway timeout. The request took too long to process. This can happen when querying logs over too wide a block range.\\n    at new o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:52711)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:55178)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:55581)\\n    at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:61725)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:61005\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:61129)\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:62138\"\n}\n  at new o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:52711)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:55178)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:55581)\n  at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:61725)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:61005\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:61129)\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:77:62138"
}
```

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by agatsoh** [comment]
I had encountered this error while syncing on the brave browser though it is not reproducible now. Open if occurs again
