### ISSUE TITLE
PFS5 fails due to replacement fee too low UNDERPRICED

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2806]
## Description

```
{
    "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 123825149081000002}>",
    "event": "Task errored",
    "logger": "scenario_player.tasks.base",
    "level": "error",
    "greenlet_name": "orchestration",
    "timestamp": "2021-06-10 21:48:41.899474",
    "exception": "Traceback (most recent call last):\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:44019/api/v1/payments/0xD7bB0F9D05766c0149C1A3BE14c634310C4B7719/0xd8663C0F434386B28054aA90b46B20fEee640Ca7. Expected 200: {\"message\":\"No route between nodes found.\",\"details\":\"\"}"
}
```

```
"Traceback (most recent call last):
File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__
return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/api_base.py\", line 59, in _run\n    
f'HTTP status code \"{resp.status_code}\" while fetching {url}. 
'scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" 
while fetching 
http://127.0.0.1:44019/api/v1/payments/0xD7bB0F9D05766c0149C1A3BE14c634310C4B7719/0xd8663C0F434386B28054aA90b46B20fEee640Ca7. Expected 200: {\"message\":\"No route between nodes found.\",\"details\":\"\"}"
```
Node 0 logs
```
	2021-06-10T21:42:20.127Z [info] => retryWhile retrying { count: 0, maxRetries: 10 } Error: replacement fee too low (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":265,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8c980843b9aca008301bac7945ced7cfc56b4249296108b00dba70b1b903371d880b8640a798f2400000000000000000000000003bdc0396f469ba1ec598ae74291edd17b7235fd00000000000000000000000072cfba9c7d39fe1e4453f03bc649232b2c9f33bc00000000000000000000000000000000000000000000000000000000000001f42ba0cf93d7a45eb9768aefee7f8911bbb83d29be53639c4d765f15256a4915fe3b67a0035a695086540eb90a7a854990e06e9c19c400b073aa13534d446b49d8209bf1\"],\"id\":265,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://geth.rinkeby.ethnodes.brainbot.com:8545"}, method="sendTransaction", transaction="0xf8c980843b9aca008301bac7945ced7cfc56b4249296108b00dba70b1b903371d880b8640a798f2400000000000000000000000003bdc0396f469ba1ec598ae74291edd17b7235fd00000000000000000000000072cfba9c7d39fe1e4453f03bc649232b2c9f33bc00000000000000000000000000000000000000000000000000000000000001f42ba0cf93d7a45eb9768aefee7f8911bbb83d29be53639c4d765f15256a4915fe3b67a0035a695086540eb90a7a854990e06e9c19c400b073aa13534d446b49d8209bf1", code=REPLACEMENT_UNDERPRICED, version=providers/5.3.0)
    at Logger.makeError (/lc/index.js:8386:21)
    at Logger.throwError (/lc/index.js:8395:20)
    at checkError (/lc/index.js:13394:16)
    at JsonRpcProvider.<anonymous> (/lc/index.js:13857:47)
    at step (/lc/index.js:13339:23)
    at Object.throw (/lc/index.js:13320:53)
    at rejected (/lc/index.js:13312:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'replacement fee too low',
  code: 'REPLACEMENT_UNDERPRICED',
  error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":265,\"error\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8c980843b9aca008301bac7945ced7cfc56b4249296108b00dba70b1b903371d880b8640a798f2400000000000000000000000003bdc0396f469ba1ec598ae74291edd17b7235fd00000000000000000000000072cfba9c7d39fe1e4453f03bc649232b2c9f33bc00000000000000000000000000000000000000000000000000000000000001f42ba0cf93d7a45eb9768aefee7f8911bbb83d29be53639c4d765f15256a4915fe3b67a0035a695086540eb90a7a854990e06e9c19c400b073aa13534d446b49d8209bf1\"],\"id\":265,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://geth.rinkeby.ethnodes.brainbot.com:8545", code=SERVER_ERROR, version=web/5.3.0)
      at Logger.makeError (/lc/index.js:8386:21)
      at Logger.throwError (/lc/index.js:8395:20)
      at /lc/index.js:20904:32
      at step (/lc/index.js:20671:23)
      at Object.next (/lc/index.js:20652:53)
      at fulfilled (/lc/index.js:20643:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"jsonrpc":"2.0","id":265,"error":{"code":-32000,"message":"replacement transaction underpriced"}}\n',
    error: Error: replacement transaction underpriced
        at getResult (/lc/index.js:13419:21)
        at processJsonFunc (/lc/index.js:20947:22)
        at /lc/index.js:20879:46
        at step (/lc/index.js:20671:23)
        at Object.next (/lc/index.js:20652:53)
        at fulfilled (/lc/index.js:20643:58)
        at processTicksAndRejections (internal/process/task_queues.js:95:5) {
      code: -32000,
      data: undefined
    },
    requestBody: '{"method":"eth_sendRawTransaction","params":["0xf8c980843b9aca008301bac7945ced7cfc56b4249296108b00dba70b1b903371d880b8640a798f2400000000000000000000000003bdc0396f469ba1ec598ae74291edd17b7235fd00000000000000000000000072cfba9c7d39fe1e4453f03bc649232b2c9f33bc00000000000000000000000000000000000000000000000000000000000001f42ba0cf93d7a45eb9768aefee7f8911bbb83d29be53639c4d765f15256a4915fe3b67a0035a695086540eb90a7a854990e06e9c19c400b073aa13534d446b49d8209bf1"],"id":265,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'http://geth.rinkeby.ethnodes.brainbot.com:8545'
  }
 ```

Logs
[scenario-player-run_pfs5_too_low_capacity_2021-06-10T21:40:03.log](https://github.com/raiden-network/light-client/files/6638061/scenario-player-run_pfs5_too_low_capacity_2021-06-10T21.40.03.log)
[node_4908_000.tar.gz](https://github.com/raiden-network/light-client/files/6638068/node_4908_000.tar.gz)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
I've checked this. The `replacement fee too low` is harmless when it happens only once. It's caused by 2 or more txs getting sent at the same time with the same nonce and gasPrice, because the ETH node didn't catch up with the first tx nonce. In 5s, it's retried and properly accepted, that's why you only see `count: 0, maxRetries: 10` and not count=1,2, etc..

What happens here is that there're 2 transfers, the first one succeeds and the second one gives `No route between nodes`. When checking node1 (the first expected mediator on the 2nd transfer), we can see in the end of the logs:
```
...
2021-06-10T21:46:49.996Z [info] => action     { type: 'block/new', payload: { blockNumber: 8741698 } }
2021-06-10T21:46:50.508Z [info] => action     {
  type: 'channel/deposit/success',
  payload: {
    id: 1143,
    participant: '0x03BdC0396f469ba1eC598Ae74291EDd17b7235fD',
    totalDeposit: BN(1000000000000000000),
    txHash: '0xbb6c70b0da4f8bbdd7cd2863c39bf7d0a01b40521322a7dd233a06ad67089827',
    txBlock: 8741696,
    confirmed: undefined
  },
  meta: {
    tokenNetwork: '0x5CEd7CfC56B4249296108B00DbA70b1b903371D8',
    partner: '0x03BdC0396f469ba1eC598Ae74291EDd17b7235fD'
  }
}
2021-06-10T21:47:49.998Z [info] => action     { type: 'block/stale', payload: { stale: true } }
127.0.0.1 - - "GET /api/v1/channels/0xD7bB0F9D05766c0149C1A3BE14c634310C4B7719/0x930Cbf0bc0bc5B07364B5fe6547187ffA318dce3 HTTP/1.1" 200 375 "-" "python-requests/2.25.1"
2021-06-10T21:48:41.905Z [info] => Stopping raiden...
```

Look at the times. The deposit from node0 on this channel was still confirming, when no `block/new` events came anymore; of course, as expected, if we don't detect new blocks, the deposit won't get confirmed, and after ~60s, `block/stale` action will disable receiving until we see blocks again (it means ETH node seems stuck/stale/behind sync). Of course, this doesn't happen in 2min, the node0 transfer fails because node1 couldn't confirm the deposit nor send its `PFSCapacityUpdate` which would let PFS knows about the route, and the nodes are shut down.

The issue here is NOT in LC. It was happily fetching blocks, and then they stopped comming. This may be caused by our Rinkeby's geth node getting overwhelmed and simply not replying the requests, or actually lagging behind (2min here) the blockchain's HEAD. Either way, as we can see, there's no error nor logs besides our client rightfully detecting staleness.

I'll close this issue, since there's nothing we can do in our side. It's at most an infrastructure issue.
