### ISSUE TITLE
Replacement tx gas price to low

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2843]
Seen by Olli on the Raspvberry Pi Nano:

Eth node is BB parity on goerli.

[nanopi_raiden.txt](https://github.com/raiden-network/light-client/files/6747839/nanopi_raiden.txt)

```
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32010,\"message\":\"Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.\"},\"id\":2108}\n", error={"code":-32010}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf8a8298459682f0082b57f9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b3000000000000000000000000b9ccdeb57271e6db320f75e68e3a60d24f566f6dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2ea0ea2e8e096b71281c7500b36511234f4ab0d771125af68c79f209efd77add0f44a03e9725bd855e4a8f0ec31461c4a210c436d49db1108b2ffb49a2ed356a0fdd24\"],\"id\":2108,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://parity.goerli.ethnodes.brainbot.com:8545", code=SERVER_ERROR, version=web/5.3.0)
    at Logger.makeError (/home/pi/bundle/index.js:8387:21)
    at Logger.throwError (/home/pi/bundle/index.js:8396:20)
    at /home/pi/bundle/index.js:17160:32
    at step (/home/pi/bundle/index.js:16927:23)
    at Object.next (/home/pi/bundle/index.js:16908:53)
    at fulfilled (/home/pi/bundle/index.js:16899:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'processing response error',
  code: 'SERVER_ERROR',
  body: '{"jsonrpc":"2.0","error":{"code":-32010,"message":"Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce."},"id":2108}\n',
  error: Error: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.
      at getResult (/home/pi/bundle/index.js:13421:21)
      at processJsonFunc (/home/pi/bundle/index.js:17203:22)
      at /home/pi/bundle/index.js:17135:46
      at step (/home/pi/bundle/index.js:16927:23)
      at Object.next (/home/pi/bundle/index.js:16908:53)
      at fulfilled (/home/pi/bundle/index.js:16899:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: -32010,
    data: undefined
  },
  requestBody: '{"method":"eth_sendRawTransaction","params":["0xf8a8298459682f0082b57f9459105441977ecd9d805a4f5b060e34676f50f80680b844095ea7b3000000000000000000000000b9ccdeb57271e6db320f75e68e3a60d24f566f6dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff2ea0ea2e8e096b71281c7500b36511234f4ab0d771125af68c79f209efd77add0f44a03e9725bd855e4a8f0ec31461c4a210c436d49db1108b2ffb49a2ed356a0fdd24"],"id":2108,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'http://parity.goerli.ethnodes.brainbot.com:8545',
  transaction: {
    nonce: 41,
    gasPrice: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0xb57f', _isBigNumber: true },
    to: '0x59105441977ecD9d805A4f5b060E34676F50F806',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x095ea7b3000000000000000000000000b9ccdeb57271e6db320f75e68e3a60d24f566f6dffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
    chainId: 5,
    v: 46,
    r: '0xea2e8e096b71281c7500b36511234f4ab0d771125af68c79f209efd77add0f44',
    s: '0x3e9725bd855e4a8f0ec31461c4a210c436d49db1108b2ffb49a2ed356a0fdd24',
    from: '0x00D384EF74575E97884215e9f39142228c7ACfa8',
    hash: '0xfe8399d09b846b75324303f05f39780539b01d44be7f230c8e98015d833680ab',
    type: null
  },
  transactionHash: '0xfe8399d09b846b75324303f05f39780539b01d44be7f230c8e98015d833680ab'
}
```

**Comment by palango** [comment]
Parity was still on a non-london compatible version.
