### ISSUE TITLE
Flakyness in e2e test

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2917]
While testing the coop settle with an updated PC, we got reports that the following error happens occasionally (~every third run):

```
FAIL tests/e2e/e2e.spec.ts (16.359 s)
  e2e
    ✕ scenario (61 ms)

  ● e2e › scenario

    thrown: Object {
      "reason": [ConnectionError: request failed: socket hang up],
    }

      139 |    *
      140 |    */
    > 141 |   test('scenario', async () => {
          |   ^
      142 |     await depositToUDC(raiden);
      143 |
      144 |     /*

      at new Spec (../node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tests/e2e/e2e.spec.ts:141:3)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        19.689 s, estimated 158 s
Ran all test suites matching /tests\/e2e/i.
```

**Comment by andrevmatos** [comment]
This wasn't seen in any of the tests runs on the last 3 PRs I created. I think it was some local flakyness which either got fixed in the environment, by one of the early PRs or by the auto-dependency upgrades. I think this can be closed.
