### ISSUE TITLE
Mediated transfer: Target is not online

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#396]
Happens in this PR: https://github.com/raiden-network/light-client/pull/392

## Steps to Reproduce
1. Start raiden client (here: `0x30FcED14DbcbB91A6c2ED31C42C4240056974CEd`)
2. Start 2nd raiden client (here: `0x1D3810ce695AbbD6Eb70FC4ccBbDde664667e071`)
3. Start light client (here: `0x360611bB4562C2C0B65FB6C2D552ED2d1cBd55cc`)
4. Create & fund channel between `0x360611bB4562C2C0B65FB6C2D552ED2d1cBd55cc` and `0x30FcED14DbcbB91A6c2ED31C42C4240056974CEd`
5. Create & fund channel between `0x30FcED14DbcbB91A6c2ED31C42C4240056974CEd` and `0x1D3810ce695AbbD6Eb70FC4ccBbDde664667e071`
6. In Light Client click TTT token => Pay
7. Try to pay `0x1D3810ce695AbbD6Eb70FC4ccBbDde664667e071`

## Expected Result
- I get a route and can do a mediated transfer
- There is a network request to the PFS in the network tab

## Actual Result
- No request to PFS in network tab
- `PathFindFailed`: 
> "Error: PFS: target 0x1D3810ce695AbbD6Eb70FC4ccBbDde664667e071 not online
    at MergeMapSubscriber.eval [as project] (webpack-internal:///../raiden-ts/dist/path/epics.js:66:19)
    at MergeMapSubscriber._tryNext (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/mergeMap.js:71:27)
    at MergeMapSubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/mergeMap.js:61:18)
    at MergeMapSubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
    at ThrowIfEmptySubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/throwIfEmpty.js:37:26)
    at ThrowIfEmptySubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
    at TakeSubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/take.js:46:30)
    at TakeSubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
    at ReplaySubject._subscribe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/ReplaySubject.js:76:28)
    at ReplaySubject.Observable._trySubscribe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Observable.js:50:25)
    at ReplaySubject.Subject._trySubscribe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subject.js:100:51)
    at ReplaySubject.Observable.subscribe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Observable.js:36:22)
    at TakeOperator.call (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/take.js:30:23)
    at AnonymousSubject.Observable.subscribe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Observable.js:31:31)
    at ThrowIfEmptyOperator.call (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/throwIfEmpty.js:23:23)
    at AnonymousSubject.Observable.subscribe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Observable.js:31:31)"

## Additional Infos (Optional) 
- Matrix: All clients use https://transport04.raiden.network
- PFS: All clients use https://pfs-goerli-with-fee.services-test.raiden.network
- Raiden Client: v0.200.0-rc1

![pfs-mediated](https://user-images.githubusercontent.com/3169205/66916696-1266fa80-f01c-11e9-8d58-a78a1e735ee4.png)

**Comment by nephix** [comment]
Issue was fixed within #392 
We need to fetch the availability before fetching suitable routes
