### ISSUE TITLE
Hub node suggested in README is offline

### ISSUE THREAD

**Issue by czepluch** [raiden-network/light-client#924]
When following the docs, the address suggested to be used as a hub node shows that it's offline. The line in question is this one: https://github.com/raiden-network/light-client/blame/master/README.md#L172

## Steps to Reproduce
1. Follow the guide of the dapp and use the address provided here: https://github.com/raiden-network/light-client/blame/master/README.md#L172

## Expected Result
- The node is online and works

## Actual Result
- The node is offline

## Suggested fix
Maintain a node that is always available as a hub for testing etc.

**Comment by kelsos** [comment]
@czepluch This has been a request and something we have been discussing for a while now. Manuel started working on the hub in the past so that we could use it for this exact reason but there were some problems and now it seems to be stuck in limbo.

**Comment by christianbrb** [comment]
@mat7ias Could you check, if your node is running? Thanks a lot :)

**Comment by andrevmatos** [comment]
Also, TTT address is still from old 0.33 contracts, we need to update.

**Comment by mat7ias** [comment]
@christianbrb I completly missed this notification, sorry about the delayed response. The node had crashed for a while before I realized and started it back up again. But testing transfers now to the node (running Narcoleptic Neo) from the light client, it seems they're unsuccessful. Is that because I need to select the token network registry for v0.36.0?
If so that seems not to work with Narcoleptic Neo: ```[TokenNetworkRegistry]Address 0x9b0c8C8C75904CEf5B7a8dbF59c3459Ea85c6526 has wrong code.. Please update your Raiden installation.```

**Comment by kelsos** [comment]
@mat7ias we are in the process of setting a test environment currently #928 so if you are using docker for your node, there is a version that is already tagged that you could use.

**Comment by mat7ias** [comment]
@kelsos I haven't used docker with Raiden previously. I'm trying it now and am having trouble starting it with geth running on the same server. It cancels after I select and unlock the account (0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6):
```docker: Error response from daemon: driver failed programming external connectivity on endpoint competent_cerf (2b9677333fbd5b2680953d2fd18d2d4f6260d84d1ef304af1eb00b95707ddbf9): Error starting userland proxy: listen tcp 0.0.0.0:8545: bind: address already in use.
ERRO[0000] error waiting for container: context canceled```

I'm able to start the node if I connect it to infura except the synchronization seems strange, it seems to be synchronizing for a long time after Raiden starts:
```2020-02-11 10:24:50.053058 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.064124354051335 blocks_to_sync=1 elapsed=15.594699 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:25:05.646033 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06413141913018428 blocks_to_sync=1 elapsed=15.592981 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:25:21.336279 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06373397337538755 blocks_to_sync=1 elapsed=15.690219 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:25:47.393007 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.03837776275757428 blocks_to_sync=1 elapsed=26.056756 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:26:02.951267 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06427454382910068 blocks_to_sync=1 elapsed=15.558259 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:26:18.702630 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06348656938450342 blocks_to_sync=1 elapsed=15.751363 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:26:34.338195 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06395682453854512 blocks_to_sync=1 elapsed=15.635548 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:26:50.232199 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06291678041496258 blocks_to_sync=1 elapsed=15.894011 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:27:05.965194 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06356064845844771 blocks_to_sync=1 elapsed=15.733005 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:27:32.272276 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.03801257775377748 blocks_to_sync=1 elapsed=26.307082 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:27:47.851359 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06418867155959793 blocks_to_sync=1 elapsed=15.579073 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:28:03.496938 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.0639157743491936 blocks_to_sync=1 elapsed=15.64559 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
2020-02-11 10:28:19.084156 [info     ] Synchronizing blockchain events [raiden.raiden_service] blocks_per_second=0.06415514253187628 blocks_to_sync=1 elapsed=15.587215 greenlet_name=AlarmTask._run node:0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
```

**Comment by mat7ias** [comment]
It crash at one point as well, not sure if it was a one off:
```2020-02-11 09:48:29.648307 [critical ] Unhandled exception when processing endpoint request [raiden.api.rest] node=0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1810, in dispatch_request
    self.raise_routing_exception(req)
  File "/opt/venv/lib/python3.7/site-packages/flask/app.py", line 1793, in raise_routing_exception
    raise request.routing_exception
  File "/opt/venv/lib/python3.7/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/opt/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1785, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2020-02-11 09:48:30.664216 [info     ] 193.169.253.90 - - [2020-02-11 09:48:30] "POST / HTTP/1.1" 500 161 1.016260 [raiden.api.rest.pywsgi]
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/opt/venv/lib/python3.7/site-packages/raiden/api/rest.py", line 442, in _run
    self.wsgiserver.serve_forever()
  File "/opt/venv/lib/python3.7/site-packages/gevent/baseserver.py", line 389, in serve_forever
    self._stop_event.wait()
  File "src/gevent/event.py", line 133, in gevent._event.Event.wait
  File "src/gevent/_abstract_linkable.py", line 208, in gevent.__abstract_linkable.AbstractLinkable._wait
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2020-02-11T09:48:30Z <Greenlet "APIServer|Greenlet-3" at 0x7f8131cec050: _run> failed with MethodNotAllowed```

**Comment by kelsos** [comment]
@mat7ias I have a docker configuration with `docker-compose` that I use at my desktop for development. I usually use it with a local `geth` node. I will post it in the evening when I get back home.

I was also confused in the beginning with the synchronization message. It seems to be normal though.

I will provide full instructions on how to set up a node as part of the test environment as soon as I am done with #928.  

The last stack trace is because something tried to post at the root URL of the rest API which is not allowed. This should not crash Raiden, would it be easy for you to verify if it happens on the latest master of Raiden or if there is already an issue?

**Comment by mat7ias** [comment]
@kelsos I'm able to send token transfers successfully to the node (ENS: mat7ias.eth), from light client, now. Haven't had it crash again since this first time.

> This should not crash Raiden, would it be easy for you to verify if it happens on the latest master of Raiden or if there is already an issue?

I'll try and will let you know!

**Comment by mat7ias** [comment]
Everything seems to run smoothly, I'm not sure what happened the first time. Maybe I gave some accidental input 🤪

**Comment by kelsos** [comment]
@mat7ias Good to know thank you.

**Comment by kelsos** [comment]
@mat7ias with #1044 we moved everything to the new test environment. Would you be interested to upgrading your node configuration? you can find the instructions here https://lightclient.raiden.network/docs/connecting/

**Comment by mat7ias** [comment]
@kelsos 
```FATAL: An unexpected exception occured. A traceback has been written to /tmp/raiden-exception-2020-03-04T09-13griikm_c.txt                            The Pathfinding Service at https://pfs.raidentransport.test001.env.raiden.network is not registered with the Service Registry at 0x1d238cdacA8fFFD56F722B587aA010d6B438B077 or the registered URL (raidentransport.test001.env.raiden.network) doesn't match the given URL https://pfs.raidentransport.test001.env.raiden.network. Raiden will shut down. Please select a registered Pathfinding Service.
ReturnCode.FATAL```

**Comment by kelsos** [comment]
Did you also use the tagged docker image?

**Comment by mat7ias** [comment]
I did docker pull raidennetwork/raiden:testenv001 and it returned that image was up to date. Should I follow the 'Running the python client from source' instructions instead?

**Comment by kelsos** [comment]
@mat7ias can you see the version reported in raiden when the container starts?

**Comment by mat7ias** [comment]
@kelsos I didn't check, I've now run it from source instead. It's up and I tested light client token transfers to it which was successful.

**Comment by kelsos** [comment]
Some times I had issues where the container was in an older version that was not updating properly.

**Comment by christianbrb** [comment]
We have got the Raiden Hub (https://hub.raiden.network/) now and the docs are changed.
